In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
A = np.array([[1,13,4,5, -6],[-9,4,12,0,2],[45,4,3,2,1], [3,-9,15,6,22],[3,5,0,-7,12]])
A

array([[ 1, 13,  4,  5, -6],
       [-9,  4, 12,  0,  2],
       [45,  4,  3,  2,  1],
       [ 3, -9, 15,  6, 22],
       [ 3,  5,  0, -7, 12]])

In [3]:
# Find the sum of all elements in an array
ans1 = np.sum(A)

In [4]:
m1 = np.array([[-7, -6,  3, -5],
       [ 7,  0,  4,  0],
       [ 6, -1,  1,  1]])
m2 = np.array([[  6,  -7,  -3,  -9],
       [ -8,   1,  -4,   2],
       [-10,   1,  -7,   9]])

In [5]:
# Calculate the difference between matrices m1 and m2.
ans2 = m1 - m2

In [6]:
b = np.array([[ -6,  -7,  -5,   0],
       [-15,   2, -13,  -5],
       [  8,   4,  10,   8],
       [ -1,  -9,   7,  -4]])

In [7]:
# Find the sum of all matrix elements whose absolute value is greater than 5. You can use a  for  loop, but try using numpy methods (i.e. this), since the numpy library is very fast and effective in manipulating data.
ans3 = np.sum(np.where(np.absolute(b) > 5, b, 0))

In [8]:
n = np.array([[ -4,  -1,   3,  -7,   6,  -9,   5,  -9,  -7,   0],
       [-12,   3, -12,  -7,   2,  -4,   8,  13,   9,   3],
       [ -2,  -1, -15, -10,   7,   5,   7, -13,  -9,   6],
       [  7,  11,  -5,  -6,  -9,  -1,   3,  10, -15,  -6],
       [ -3,  -4,   4, -13,   4, -13,  10,  -6,  -8,  13],
       [  7, -13,  -4,   3,   4,  13, -13,   4,  -9, -10],
       [ -5,  13,  -9, -15,  11,   2,   7, -14, -14,   2],
       [ -4,  -6,  12,  10,  13,  -3,  12, -15,   5,  -2],
       [ -1,   8,   3,   7,  11,  -3,   6,  12,  12, -13],
       [ 12,  11,  12,  11,   1, -14,   2,   6,  -9,  -3]])
z = np.array([[-15,   5, -15,  10,  -3,  12,  -6, -15,   6,   3],
       [ 12,  -4,   6, -11,   5,   3,   3,  12, -15,  -6],
       [-11, -11, -10,   9,  -8, -14, -14,   7,  -2,  11],
       [  5,  -4,  11,   0,   8,  -9, -15, -11,   7, -10],
       [ -6,  -9,  -3, -13, -11,  -9,   7,  -7,   9,   4],
       [ 10,  12,   4,  -7,   1,   0,  -1,  11,  -4,  11],
       [-14,   2,  -8,  11,  -9,   5, -14,  10,  -6,  -9],
       [ -5,  10, -10,  -1,  -9, -12,  12,  14,   4,   2],
       [ -1, -13,  10,  11,  12, -14,   9,  12,  12,  -5],
       [  2,   6, -13,  -5,  -2,  -2,   0,  14,   7,  14]])

In [9]:
# Find the product of two matrices. Remember that it is better to use  matmul, or @,  for  𝐥𝐚𝐫𝐠𝐞𝐫 𝐝𝐢𝐦𝐞𝐧𝐬𝐢𝐨𝐧  matrices.
ans4 = np.matmul(n,z)

In [10]:
A = np.array([[  7,   8, -15,   8,  11,   7],
       [ -5,  -9,  13,  -3, -15, -11],
       [ -3,   0,  10,  -5,   3,  -8],
       [ 10,   1,   7, -11,  10,  -3],
       [ 11,   9,  -6, -14,  10, -11],
       [  6,  -4,  -4,  -9,  -6,  -7]])
A

array([[  7,   8, -15,   8,  11,   7],
       [ -5,  -9,  13,  -3, -15, -11],
       [ -3,   0,  10,  -5,   3,  -8],
       [ 10,   1,   7, -11,  10,  -3],
       [ 11,   9,  -6, -14,  10, -11],
       [  6,  -4,  -4,  -9,  -6,  -7]])

In [11]:
# Create an identity matrix of the necessary size and subtract it from A.
ans5 = A -  np.identity(A.shape[0])

In [12]:
A = np.array([[ 0, -2,  0, -2],
       [-2,  0, -4,  4],
       [-1, -5, -2,  2],
       [ 3, 1, 2,  1]])

In [13]:
b = np.array([-4,  1,  4,  2])

In [14]:
# Find the solution to system Ax = b, use matrix inverse.
x = np.dot(np.linalg.inv(A),b)

In [15]:
from scipy.linalg import lu

In [16]:
m = np.array([[ 12, -13,   2,   2, -11],
       [  1,   4,  11,  11,  -5],
       [ 13,  -5,   9,  12,  -2],
       [  5, -13,  12,   3,   5],
       [ -9,  11,  -1,  -6,  -5]])
m

array([[ 12, -13,   2,   2, -11],
       [  1,   4,  11,  11,  -5],
       [ 13,  -5,   9,  12,  -2],
       [  5, -13,  12,   3,   5],
       [ -9,  11,  -1,  -6,  -5]])

In [17]:
P, L, U = lu(m)#your code here

In [18]:
assert(np.allclose(((P@L)@U), m)) # check if we get the original matrix

In [19]:
U = U.flatten()