In [16]:
import numpy as np
from scipy.linalg import lu

In [17]:
# vectors
a = np.array([1,4,5])
b = np.array([-1,4, 53])
print(a)
print(b)

# vectors operations
c = a + b
d = a * b
print(c)
print(d)

[1 4 5]
[-1  4 53]
[ 0  8 58]
[ -1  16 265]


In [18]:
# matrices
m1 = np.array([[[1,4], [-5,8]]])
m2 = np.array([[[7,-6], [-11,2]]])
print(m1)
print(m2)

# matrices operations
msum = m1+m2
product = np.dot(m1,m2)
print(msum)
print(product)

[[[ 1  4]
  [-5  8]]]
[[[  7  -6]
  [-11   2]]]
[[[  8  -2]
  [-16  10]]]
[[[[ -37    2]]

  [[-123   46]]]]


In [19]:
# zeros matrix
zeros = np.zeros((2,3))
print(zeros)

# identity matrix
i = np.identity(3)
print(i)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# inverse, system of equation
a = np.array([[-1,3],[3,5]])
b = np.array([[3],[7]])

inv = np.linalg.inv(a)

x = np.dot(inv, b)

print(x)

[[0.42857143]
 [1.14285714]]


In [23]:
# PLU decomposition using scipy
B = np.array([[0,0,1], [0,2,2], [3,0,4]])

# PLU
P, L, U = lu(B)

# outputs true
# PLU = B
np.allclose( np.dot( np.dot(P,L), U ), B )

True

In [30]:
# Covered Python methods
# for higher dimension arrays using numpy.matmult is more preferable.
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
np.matmul(a, b) # also can be written as a @ b

array([[4, 1],
       [2, 2]])

In [28]:
a = np.array([[1,2],[3,4]])
# sum_of_elements is 10
sum_of_elements = np.sum(a)

k = -9
abs_k = np.abs(k) #abs_k is 9

# random matrix of size 4x4 with values from -15 to 15
m1 = np.random.randint(low=-15,high=15, size=(4, 4))
#replace all values that are greater than 0 with 1
filted_m1 = np.where(m1 < 0, m1, 1) 